# Generated by Django 2.2 on 2019-06-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190610_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_date', '-updated', 'timestamp']},
        ),
    ]
